name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest  # GitHub-hosted runner
    steps:
      - uses: actions/checkout@v3

      - name: Configure NODE
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Download NPM dependencies
        run: npm install
      - name: Compile TS files
        run: npm run compile