name: SETUP

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  configure-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configure NODE
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install (cmd)
        shell: cmd
        run: ./configure.bat
      - name: Verify download
        uses: andstor/file-existence-action@v3
        with:
          files: "ffmpeg.exe, ffprobe.exe, node_modules"
          fail: true
      - name: Delete download files
        shell: cmd
        run: |
          del /f /q ffmpeg.exe ffprobe.exe
          rmdir /s /q node_modules
      - name: Install (powershell)
        shell: pwsh
        run: ./configure.bat
      - name: Verify download
        uses: andstor/file-existence-action@v3
        with:
          files: "ffmpeg.exe, ffprobe.exe, node_modules"
          fail: true

  configure-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configure NODE
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install
        run: |
          chmod u+x configure
          ./configure
      - name: Verify download
        uses: andstor/file-existence-action@v3
        with:
          files: "ffmpeg, ffprobe, node_modules"
          fail: true

  configure-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configure NODE
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install
        run: |
          chmod u+x configure
          ./configure
      - name: Verify download
        uses: andstor/file-existence-action@v3
        with:
          files: "ffmpeg, ffprobe, node_modules"
          fail: true